[project]
requires-python = ">=3.11"
name = "SegmentBackupJob"
version = "1.0"
dependencies = [
    'segment-analytics-python==2.2.3',
    'kubernetes==29.0.0',
    'pyYAML==6.0.1',
    'openshift==0.13.2'
]